# Generated by Django 5.2.8 on 2026-01-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_artist_options_alter_track_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Артист', 'verbose_name_plural': 'Артисты'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
    ]
